module.exports = {
    BOT_USER_ID: '372392086789423104',
    BOT_CHANNEL_ID: '372365212076081164',
    ARENA_CHANNEL_ID: '619846213650612255',
    LOGGER_CHANNEL_ID: '473176714869080065',
    BOT_CATEGORY_ID: '372246646831972352',
    GUILD_ID: '371533518653751306',
    DEV_ID: '162434234357645312',
    DEATH_IMAGE: 'https://i.imgur.com/BVScqCl.png',
    LEVEL_UP_IMAGE: 'https://i.imgur.com/BncqEFS.png',
    ACHIEVEMENTS: {
        '1': '🥉',
        '2': '🥈',
        '3': '🥇',
    },
    LEVEL_XP_TOTALS: {
        '1': 10,
        '2': 15,
        '3': 20,
        '4': 20,
        '5': 20,
        '6': 20,
        '7': 20,
        '8': 20,
        '9': 20,
        '10': 20,

    },
    LEVEL_EMOJI: {
        '1': '1⃣',
        '2': '2⃣',
        '3': '3⃣',
        '4': '4⃣',
        '5': '5⃣',
        '6': '6⃣',
        '7': '7⃣',
        '8': '8⃣',
        '9': '9⃣',
        '10': '🔟',
    },
    NEW_PLAYER_DATA: {
        'level': 1,
        'currentxp': 0,
        'maxxp': 10,
        'currency': 5,
        'basehp': 15,
        'baseattack': 1,
        'maxhp': 1,
        'currenthp': 15,
        'defense': 0,
        'attack': 1,
        'armor': 'none equiped',
        'weapon': 'none equiped',
        'inventory': { 'health-potions': 1 },
        'quest': { 'active': false, 'type': '', 'total': null, 'progress': null, 'reward': null, 'img': '' },
        'dungeonActive': false,
        'dungeonChannel': '',
        'achievements': '',
        'lasthpbar': '',
        'Class' : 'none',
    },
    DUNGEON_DATA: {
        'dungeonID': '',
        'dungeonNumber': '',
        'players': '',
        'currentMob1': '',
        'currentMob2': '',
        'currentMob3': '',
        'progress': 1,
        'lastMessageId': '',
        'currentFight': '',
        'total_xp': 0,
        'total_reward': 0,
    },
    CLASSES: [
        { 'name': 'Assasain', 'ability': 'Critical Chance %', 'value': 50 },
        { 'name': 'Healer', 'ability': 'Heal ❤️', 'value': 10 },
        { 'name': 'Tank', 'ability': 'Armor Bonus 🛡', 'value': 50 },
        { 'name': 'Sneaker', 'ability': 'Passive Evasion 🏃‍', 'value': 25 },
        { 'name': 'Sharp Shooter', 'ability': 'Passive Damage Bonus ⚔', 'value': 10 }],
};

